[package]
name = "rdkafka-sys"
version = "0.9.4-0"
authors = ["Federico Giraud <giraud.federico@gmail.com>"]
build = "build.rs"
links = "rdkafka"
repository = "https://github.com/fede1024/rust-rdkafka"
license = "MIT"
description = "Native bindings to the librdkafka library"
keywords = ["kafka", "rdkafka"]
categories = ["external-ffi-bindings"]

[dependencies]
lz4-sys = { git = "https://github.com/Roguelazer/lz4-rs", branch = "new_liblz4" }
libz-sys = "^ 1.0"
openssl-sys = "~ 0.9.0"

[build-dependencies]
num_cpus = "~ 0.2.0"

[lib]
name = "rdkafka_sys"
path = "src/lib.rs"

[features]
default = []

ssl = []
sasl = ["ssl"]
